In [ ]:
import numpy as np
from itertools import combinations


def h_to_v_rep(A, b):
    """
    Obtiene la V-representation de un cuerpo convexo a partir de la H-representation
    A : Matriz de coeficientes (m x n)
    b : Vector (m)
    """
    m, n = A.shape # n debería ser 3
    vertices = []

    # Buscamos intersecciones de 3 planos
    for indice in combinations(range(m),n):
        # Seleccionamos las 3 filas correspondientes a los planos
        A_sub = A[list(indice)]
        b_sub = b[list(indice)]

        try:
            


        except:


        
    return vertices

from convex_hull import generate_convex_hull

verts = [(0,0,0), (0,1,0), (0,0,1), (0,1,1),
         (2,0,1), (2,1,0), (2,0,1), (2,1,1)]

A, b = generate_convex_hull(verts)
print(A)
print(b)

A_sub , b_sub = h_to_v_rep(A,b)
print(A_sub)
print(b_sub)

[[ 3.33333333e-01 -6.66666667e-01 -6.66666667e-01]
 [-5.20954874e-11 -1.00000000e+00 -1.27041525e-11]
 [ 2.80000630e-11 -6.85254031e-11 -1.00000000e+00]
 [ 1.75857107e-11  1.00000000e+00 -1.53620450e-10]
 [ 1.03143707e-11 -3.96181756e-01  9.18172106e-01]
 [ 2.06372697e-11 -2.65365507e-11  1.00000000e+00]
 [ 9.96186710e-01 -6.16929445e-02 -6.16929444e-02]
 [ 1.00000000e+00 -8.69264660e-11  1.36806122e-11]
 [-1.26543220e-12  1.72688530e-11  1.00000000e+00]
 [-3.42139650e-11  1.00000000e+00 -5.00210984e-11]
 [-1.00000000e+00 -4.91729171e-11  9.11207381e-11]
 [-1.00000000e+00  6.67979623e-11 -2.48501414e-11]]
[-4.42276216e-11 -4.25539918e-11  6.88405828e-12  1.00000000e+00
  9.18172106e-01  1.00000000e+00  1.93068048e+00  2.00000000e+00
  1.00000000e+00  1.00000000e+00  6.13427678e-11  6.13427678e-11]
[[-3.42139650e-11  1.00000000e+00 -5.00210984e-11]
 [-1.00000000e+00 -4.91729171e-11  9.11207381e-11]
 [-1.00000000e+00  6.67979623e-11 -2.48501414e-11]]
[1.00000000e+00 6.13427678e-11 6.1342